services:
  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
      #- ./mongod.conf:/etc/mongod.conf # Commented out as it might not exist or be needed with default config

  nodejs:
    build: .
    container_name: dockerised-nodejs
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    #command: node seeds/seed.js # You might want to run seeds separately or via entrypoint
